|apros;None;;;0;;pub/runtime/cache;;*;9126
|beneficiaryForm;Table;8;beneficiary;0;pub/runtime/crud/Tablexx1xxbeneficiaryForm;pub/runtime/cache;;*;9129
|beneficiaryGrid;Table;8;beneficiary;0;pub/runtime/crud/Tablexx1xxbeneficiaryGrid;pub/runtime/cache;;*;9130
|benIdForm;Table;8;ben_id;0;pub/runtime/crud/Tablexx1xxbenIdForm;pub/runtime/cache;;*;9131
|benIdGrid;Table;8;ben_id;0;pub/runtime/crud/Tablexx1xxbenIdGrid;pub/runtime/cache;;*;9132
|benNameForm;Table;8;ben_name;0;pub/runtime/crud/Tablexx1xxbenNameForm;pub/runtime/cache;;*;9133
|benNameGrid;Table;8;ben_name;0;pub/runtime/crud/Tablexx1xxbenNameGrid;pub/runtime/cache;;*;9134
|clientContactForm;Table;7;client_contact;0;pub/runtime/crud/Tablexx1xxclientContactForm;pub/runtime/cache;;*;9192
|clientContactGrid;Table;7;client_contact;0;pub/runtime/crud/Tablexx1xxclientContactGrid;pub/runtime/cache;;*;9193
|clientForm;Table;7;client;0;pub/runtime/crud/Tablexx1xxclientForm;pub/runtime/cache;;*;9190
|clientGrid;Table;7;client;0;pub/runtime/crud/Tablexx1xxclientGrid;pub/runtime/cache;;*;9191
|codeForm;Table;8;code;0;pub/runtime/crud/Tablexx1xxcodeForm;pub/runtime/cache;;*;9135
|codeGrid;Table;8;code;0;pub/runtime/crud/Tablexx1xxcodeGrid;pub/runtime/cache;;*;9136
|companyForm;Table;8;company;0;pub/runtime/crud/Tablexx1xxcompanyForm;pub/runtime/cache;;*;9137
|companyGrid;Table;8;company;0;pub/runtime/crud/Tablexx1xxcompanyGrid;pub/runtime/cache;;*;9138
|companyIsinForm;Table;8;company_isin;0;pub/runtime/crud/Tablexx1xxcompanyIsinForm;pub/runtime/cache;;*;9139
|companyIsinGrid;Table;8;company_isin;0;pub/runtime/crud/Tablexx1xxcompanyIsinGrid;pub/runtime/cache;;*;9140
|dashboard;None;;;0;;pub/runtime/cache;;*;9171
|datasetForm;Table;8;dataset;0;pub/runtime/crud/Tablexx1xxdatasetForm;pub/runtime/cache;;*;9141
|datasetGrid;Table;8;dataset;0;pub/runtime/crud/Tablexx1xxdatasetGrid;pub/runtime/cache;;*;9142
|dibAdmin;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7129
|dibAuditTrailForm;Table;1;pef_audit_trail;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibAuditTrailForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7969
|dibAuditTrailGrid;Table;1;pef_audit_trail;0;>/dropins/dibAdmin/DAuditTrailCrud;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7683
|dibChartJsdibReport;None;;;0;;pub/runtime/cache;;*;9216
|dibComponentForm;Table;1;pef_component;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibComponentForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7970
|dibComponentGrid;Table;1;pef_component;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibComponentGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7246
|dibContainerEventForm;Table;1;pef_container_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerEventForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7972
|dibContainerEventGrid;Table;1;pef_container_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerEventGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7135
|dibContainerFilterForm;Table;1;pef_container_filter;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerFilterForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7973
|dibContainerFilterGrid;Table;1;pef_container_filter;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerFilterGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7252
|dibContainerForm;Table;1;pef_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7971
|dibContainerGrid;Table;1;pef_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7225
|dibContainerSettingForm;Table;1;pef_container_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerSettingForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7974
|dibContainerSettingGrid;Table;1;pef_container_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContainerSettingGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7134
|dibContentTypeForm;Table;1;pef_content_type;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContentTypeForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7975
|dibContentTypeGrid;Table;1;pef_content_type;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibContentTypeGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7976
|dibCreateContainer;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6674
|dibCreateFromSql;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;3080
|dibDashboard;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7170
|dibDatabaseForm;Table;1;pef_database;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDatabaseForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;au,bd;*;245
|dibDatabaseGrid;Table;1;pef_database;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDatabaseGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;au,bd;*;246
|dibDatatypeForm;Table;1;pef_datatype;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDatatypeForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7977
|dibDatatypeGrid;Table;1;pef_datatype;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDatatypeGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7978
|dibdemo;None;;;0;;pub/runtime/cache;;*;9189
|dibDesigner;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7126
|dibDesignerAddEvent;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6297
|dibDesignerComponentTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7143
|dibDesignerContainerHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7133
|dibDesignerContainers;Table;1;pef_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerContainers;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7130
|dibDesignerItemHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7173
|dibDesignerItemPermFilesHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8651
|dibDesignerItems;Table;1;pef_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerItems;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd,bu,bc;*;7131
|dibDesignerItemTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7144
|dibDesignerOverComponentTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6655
|dibDesignerOverviewComponentTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6656
|dibDesignerOverviewItemsTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8527
|dibDesignerPermFilesHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8650
|dibDesignerPreviewHolder;Table;1;pef_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerPreviewHolder;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7168
|dibDesignerQuickEdit;Table;1;pef_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerQuickEdit;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd,bu,bc;*;7171
|dibDesignerToolHolder;Table;1;pef_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerToolHolder;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd,bu,bc;*;8307
|dibDesignerTreeItemTabs;Table;1;pef_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignerTreeItemTabs;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7172
|dibDesignFeatureForm;Table;1;pef_design_feature;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignFeatureForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7981
|dibDesignFeatureGrid;Table;1;pef_design_feature;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignFeatureGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7665
|dibDesignForm;Table;1;pef_design;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7979
|dibDesignGrid;Table;1;pef_design;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7980
|dibDesignValuesForm;Table;1;pef_design_values;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignValuesForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7982
|dibDesignValuesGrid;Table;1;pef_design_values;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDesignValuesGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7232
|dibDocs;Table;1;pef_docs;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDocs;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8064
|dibDocsForm;Table;1;pef_docs;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDocsForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7984
|dibDocsGrid;Table;1;pef_docs;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDocsGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7966
|dibDocsTree;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;3214
|dibDropinForm;Table;1;pef_dropin;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDropinForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7985
|dibDropinGrid;Table;1;pef_dropin;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibDropinGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7667
|dibErrorLog;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8578
|dibexComponentGrid;Table;1;test;0;pub/dropins/dibExamples/crud/Tablexx1xxdibexComponentGrid;pub/dropins/dibExamples/cache;;*;7162
|dibexComponents;Table;1;test;0;pub/dropins/dibExamples/crud/Tablexx1xxdibexComponents;pub/dropins/dibExamples/cache;;*;7142
|dibexContainerDropins;Table;1;test;0;pub/dropins/dibExamples/crud/Tablexx1xxdibexContainerDropins;pub/dropins/dibExamples/cache;;*;7161
|dibexEvents;None;;;0;;pub/dropins/dibExamples/cache;;*;7146
|dibexLayout;None;;;0;;pub/dropins/dibExamples/cache;;*;7145
|dibexLayoutNestedComponents;None;;;0;;pub/dropins/dibExamples/cache;;*;8061
|dibexLayoutTabsSubcontainer;None;;;0;;pub/dropins/dibExamples/cache;;*;8060
|dibexLazyLoad;None;;;0;;pub/dropins/dibExamples/cache;;*;7152
|dibexLazyLoadHtml;None;;;0;;pub/dropins/dibExamples/cache;;*;7153
|dibexPhp;None;;;0;;pub/dropins/dibExamples/cache;;*;8062
|dibexPorts;None;;;0;;pub/dropins/dibExamples/cache;;*;7154
|dibexSubChartJsHtml;None;;;0;;pub/dropins/dibExamples/cache;;*;9172
|dibexSubContainers;Table;1;test_company;0;pub/dropins/dibExamples/crud/Tablexx1xxdibexSubContainers;pub/dropins/dibExamples/cache;;*;7155
|dibFieldForm;Table;1;pef_field;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFieldForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7986
|dibFieldGrid;Table;1;pef_field;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFieldGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7987
|dibFiles;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6636
|dibFileSettingForm;Table;1;pef_file_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFileSettingForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7988
|dibFileSettingGrid;Table;1;pef_file_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFileSettingGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7989
|dibFindReplace;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6657
|dibFkForm;Table;1;pef_fk;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFkForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7990
|dibFkGrid;Table;1;pef_fk;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibFkGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7991
|dibImportForm;Table;1;pef_import;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibImportForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7992
|dibImportGrid;Table;1;pef_import;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibImportGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7993
|dibImportItemForm;Table;1;pef_import_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibImportItemForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7994
|dibImportItemGrid;Table;1;pef_import_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibImportItemGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7995
|dibItemEventForm;Table;1;pef_item_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemEventForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7997
|dibItemEventGrid;Table;1;pef_item_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemEventGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7139
|dibItemFilterForm;Table;1;pef_item_filter;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemFilterForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7998
|dibItemFilterGrid;Table;1;pef_item_filter;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemFilterGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7140
|dibItemForm;Table;1;pef_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd,bu,bc;*;7996
|dibItemGrid;Table;1;pef_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd,bu,bc;*;7256
|dibItemSettingForm;Table;1;pef_item_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemSettingForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7999
|dibItemSettingGrid;Table;1;pef_item_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibItemSettingGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7138
|dibLocalizationForm;Table;1;pef_localization;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLocalizationForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8000
|dibLocalizationGrid;Table;1;pef_localization;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLocalizationGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8001
|dibLog;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6020
|dibLoginForm;Table;1;pef_login;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLoginForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8002
|dibLoginGrid;Table;1;pef_login;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLoginGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8003
|dibLoginGroupForm;Table;1;pef_login_group;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLoginGroupForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8004
|dibLoginGroupGrid;Table;1;pef_login_group;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibLoginGroupGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8005
|dibParamForm;Table;1;pef_param;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibParamForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8006
|dibParamGrid;Table;1;pef_param;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibParamGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8007
|dibPermContainerEventForm;Table;1;pef_perm_container_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermContainerEventForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8009
|dibPermContainerEventGrid;Table;1;pef_perm_container_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermContainerEventGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7266
|dibPermContainerForm;Table;1;pef_perm_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermContainerForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8008
|dibPermContainerGrid;Table;1;pef_perm_container;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermContainerGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7137
|dibPermFieldTempForm;Table;1;pef_perm_field_temp;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermFieldTempForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8010
|dibPermFieldTempGrid;Table;1;pef_perm_field_temp;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermFieldTempGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7268
|dibPermGroupForm;Table;1;pef_perm_group;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermGroupForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8011
|dibPermGroupGrid;Table;1;pef_perm_group;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermGroupGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7270
|dibPermItemEventForm;Table;1;pef_perm_item_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermItemEventForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8013
|dibPermItemEventGrid;Table;1;pef_perm_item_event;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermItemEventGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7274
|dibPermItemForm;Table;1;pef_perm_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermItemForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8012
|dibPermItemGrid;Table;1;pef_perm_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermItemGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7141
|dibPermRecordTempForm;Table;1;pef_perm_record_temp;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermRecordTempForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8014
|dibPermRecordTempGrid;Table;1;pef_perm_record_temp;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermRecordTempGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7276
|dibPermTooltipForm;Table;1;pef_perm_tooltip;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermTooltipForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8015
|dibPermTooltipGrid;Table;1;pef_perm_tooltip;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPermTooltipGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7278
|dibPortForm;Table;1;pef_port;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPortForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8016
|dibPortGrid;Table;1;pef_port;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibPortGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7136
|dibReport;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;9204
|dibReportCurrentHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;9217
|dibReportHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;9218
|dibReusablesGrid;Table;1;test_company;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibReusablesGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7964
|dibSecurityPolicyForm;Table;1;pef_security_policy;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSecurityPolicyForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8017
|dibSecurityPolicyGrid;Table;1;pef_security_policy;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSecurityPolicyGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8018
|dibSettingForm;Table;1;pef_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSettingForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8019
|dibSettingGrid;Table;1;pef_setting;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSettingGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8020
|dibShare;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8176
|dibSql;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;6022
|dibSqlForm;Table;1;pef_sql;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSqlForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8021
|dibSqlGrid;Table;1;pef_sql;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSqlGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7759
|dibSqlItemForm;Table;1;pef_sql_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSqlItemForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8022
|dibSqlItemGrid;Table;1;pef_sql_item;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibSqlItemGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8023
|dibSystemReportMain;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;3408
|dibSystemReportMainHtml;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;3409
|dibTableDesign;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableDesign;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8529
|dibTableDesignFieldGrid;Table;1;pef_field;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableDesignFieldGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8528
|dibTableFkForm;Table;1;pef_table_fk;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableFkForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8026
|dibTableFkGrid;Table;1;pef_table_fk;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableFkGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8027
|dibTableForm;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8024
|dibTableGrid;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;8025
|dibTableOptionFieldForm;Table;1;pef_table_option_field;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableOptionFieldForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8030
|dibTableOptionFieldGrid;Table;1;pef_table_option_field;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableOptionFieldGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8031
|dibTableOptionForm;Table;1;pef_table_option;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableOptionForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8028
|dibTableOptionGrid;Table;1;pef_table_option;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableOptionGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8029
|dibTableSyncGrid;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTableSyncGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;6296
|dibtestChildForm;Table;1;test_child;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestChildForm;pub/dropins/dibExamples/cache;bu,bd;*;7151
|dibTestCompanyAsyncGrid;Table;1;test_company;0;pub/dropins/dibExamples/crud/Tablexx1xxdibTestCompanyAsyncGrid;pub/dropins/dibExamples/cache;;*;8063
|dibtestCompanyConsultantGrid;Table;1;test_company_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestCompanyConsultantGrid;pub/dropins/dibExamples/cache;;*;7156
|dibtestCompanyConsultantPopup;Table;1;test_company_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestCompanyConsultantPopup;pub/dropins/dibExamples/cache;;*;7160
|dibtestCompanyDrilldown;None;;;0;;pub/dropins/dibExamples/cache;;*;3677
|dibtestCompanyETReport;None;;;0;;pub/dropins/dibExamples/cache;;*;7148
|dibtestCompanyForm;Table;1;test_company;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestCompanyForm;pub/dropins/dibExamples/cache;;*;7961
|dibtestCompanyGrid;Table;1;test_company;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestCompanyGrid;pub/dropins/dibExamples/cache;;*;7150
|dibtestCompanySqlRptGrid;Sql;1;dibtestCompanySqlRpt;0;pub/dropins/dibExamples/crud/Sqlxx1xxdibtestCompanySqlRptGrid;pub/dropins/dibExamples/cache;;*;7159
|dibtestConsultantEventsGrid;Table;1;test_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestConsultantEventsGrid;pub/dropins/dibExamples/cache;;*;7149
|dibtestConsultantForm;Table;1;test_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestConsultantForm;pub/dropins/dibExamples/cache;;*;7157
|dibtestConsultantGrid;Table;1;test_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestConsultantGrid;pub/dropins/dibExamples/cache;;*;7147
|dibtestConsultantPortGrid;Table;1;test_consultant;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestConsultantPortGrid;pub/dropins/dibExamples/cache;;*;7166
|dibtestdibContainer;None;;;0;;pub/dropins/dibExamples/cache;;*;7163
|dibtestETEventsReport;None;;;0;;pub/dropins/dibExamples/cache;;*;8581
|dibtestHorTree;None;;;0;;pub/dropins/dibExamples/cache;;*;8178
|dibtestNestedPort;None;;;0;;pub/dropins/dibExamples/cache;;*;7167
|dibtestTestForm;Table;1;test;0;pub/dropins/dibExamples/crud/Tablexx1xxdibtestTestForm;pub/dropins/dibExamples/cache;;*;8580
|dibtestTree;None;;;0;;pub/dropins/dibExamples/cache;;*;7165
|dibTheme;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8180
|dibTooltipForm;Table;1;pef_tooltip;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTooltipForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8032
|dibTooltipGrid;Table;1;pef_tooltip;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibTooltipGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7282
|dibUnitTestForm;Table;1;pef_unit_test;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibUnitTestForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8033
|dibUnitTestGrid;Table;1;pef_unit_test;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibUnitTestGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8034
|dibValidationTypeForm;Table;1;pef_validation_type;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibValidationTypeForm;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8035
|dibValidationTypeGrid;Table;1;pef_validation_type;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxdibValidationTypeGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;8036
|importCompanyForm;Table;8;import_company;0;pub/runtime/crud/Tablexx1xximportCompanyForm;pub/runtime/cache;;*;9143
|importCompanyGrid;Table;8;import_company;0;pub/runtime/crud/Tablexx1xximportCompanyGrid;pub/runtime/cache;;*;9144
|importMandatedForm;Table;8;import_mandated;0;pub/runtime/crud/Tablexx1xximportMandatedForm;pub/runtime/cache;;*;9145
|importMandatedGrid;Table;8;import_mandated;0;pub/runtime/crud/Tablexx1xximportMandatedGrid;pub/runtime/cache;;*;9146
|importStrateForm;Table;8;import_strate;0;pub/runtime/crud/Tablexx1xximportStrateForm;pub/runtime/cache;;*;9147
|importStrateGrid;Table;8;import_strate;0;pub/runtime/crud/Tablexx1xximportStrateGrid;pub/runtime/cache;;*;9148
|importStrateHeadForm;Table;8;import_strate_head;0;pub/runtime/crud/Tablexx1xximportStrateHeadForm;pub/runtime/cache;;*;9149
|importStrateHeadGrid;Table;8;import_strate_head;0;pub/runtime/crud/Tablexx1xximportStrateHeadGrid;pub/runtime/cache;;*;9150
|inetBfaForm;Table;8;inet_bfa;0;pub/runtime/crud/Tablexx1xxinetBfaForm;pub/runtime/cache;;*;9151
|inetBfaGrid;Table;8;inet_bfa;0;pub/runtime/crud/Tablexx1xxinetBfaGrid;pub/runtime/cache;;*;9152
|mandatedClassForm;Table;8;mandated_class;0;pub/runtime/crud/Tablexx1xxmandatedClassForm;pub/runtime/cache;;*;9155
|mandatedClassGrid;Table;8;mandated_class;0;pub/runtime/crud/Tablexx1xxmandatedClassGrid;pub/runtime/cache;;*;9156
|mandatedForm;Table;8;mandated;0;pub/runtime/crud/Tablexx1xxmandatedForm;pub/runtime/cache;;*;9153
|mandatedGrid;Table;8;mandated;0;pub/runtime/crud/Tablexx1xxmandatedGrid;pub/runtime/cache;;*;9154
|mandatedSubclassForm;Table;8;mandated_subclass;0;pub/runtime/crud/Tablexx1xxmandatedSubclassForm;pub/runtime/cache;;*;9157
|mandatedSubclassGrid;Table;8;mandated_subclass;0;pub/runtime/crud/Tablexx1xxmandatedSubclassGrid;pub/runtime/cache;;*;9158
|marketCapForm;Table;8;market_cap;0;pub/runtime/crud/Tablexx1xxmarketCapForm;pub/runtime/cache;;*;9159
|marketCapGrid;Table;8;market_cap;0;pub/runtime/crud/Tablexx1xxmarketCapGrid;pub/runtime/cache;;*;9160
|nomineeForm;Table;8;nominee;0;pub/runtime/crud/Tablexx1xxnomineeForm;pub/runtime/cache;;*;9161
|nomineeGrid;Table;8;nominee;0;pub/runtime/crud/Tablexx1xxnomineeGrid;pub/runtime/cache;;*;9162
|nomShareForm;Table;8;nom_share;0;pub/runtime/crud/Tablexx1xxnomShareForm;pub/runtime/cache;;*;9163
|nomShareGrid;Table;8;nom_share;0;pub/runtime/crud/Tablexx1xxnomShareGrid;pub/runtime/cache;;*;9164
|projectForm;Table;7;project;0;pub/runtime/crud/Tablexx1xxprojectForm;pub/runtime/cache;;*;9194
|projectGrid;Table;7;project;0;pub/runtime/crud/Tablexx1xxprojectGrid;pub/runtime/cache;;*;9195
|shareForm;Table;8;share;0;pub/runtime/crud/Tablexx1xxshareForm;pub/runtime/cache;;*;9165
|shareGrid;Table;8;share;0;pub/runtime/crud/Tablexx1xxshareGrid;pub/runtime/cache;;*;9166
|skillForm;Table;7;skill;0;pub/runtime/crud/Tablexx1xxskillForm;pub/runtime/cache;;*;9196
|skillGrid;Table;7;skill;0;pub/runtime/crud/Tablexx1xxskillGrid;pub/runtime/cache;;*;9197
|staffForm;Table;7;staff;0;pub/runtime/crud/Tablexx1xxstaffForm;pub/runtime/cache;;*;9198
|staffGrid;Table;7;staff;0;pub/runtime/crud/Tablexx1xxstaffGrid;pub/runtime/cache;;*;9199
|staffProjectForm;Table;7;staff_project;0;pub/runtime/crud/Tablexx1xxstaffProjectForm;pub/runtime/cache;;*;9200
|staffProjectGrid;Table;7;staff_project;0;pub/runtime/crud/Tablexx1xxstaffProjectGrid;pub/runtime/cache;;*;9201
|staffSkillForm;Table;7;staff_skill;0;pub/runtime/crud/Tablexx1xxstaffSkillForm;pub/runtime/cache;;*;9202
|staffSkillGrid;Table;7;staff_skill;0;pub/runtime/crud/Tablexx1xxstaffSkillGrid;pub/runtime/cache;;*;9203
|summaryForm;Table;8;summary;0;pub/runtime/crud/Tablexx1xxsummaryForm;pub/runtime/cache;;*;9167
|summaryGrid;Table;8;summary;0;pub/runtime/crud/Tablexx1xxsummaryGrid;pub/runtime/cache;;*;9168
|testSqlGridGrid;Sql;1;dibtestSqlGrid;0;pub/runtime/crud/Sqlxx1xxtestSqlGridGrid;pub/runtime/cache;;*;9107
|testSqlGridGrid1;Sql;1;dibtestSqlGrid;0;pub/runtime/crud/Sqlxx1xxtestSqlGridGrid1;pub/runtime/cache;;*;9108
|tmplBase1;None;;;0;;pub/runtime/cache;;*;7236
|tmplBase2;None;;;0;;pub/runtime/cache;;*;9073
|tmplBase3;None;;;0;;pub/runtime/cache;;*;8174
|tmplBase4;None;;;0;;pub/runtime/cache;;*;9093
|tmplDashboard;None;;;0;;pub/runtime/cache;;*;7308
|tmplFormNg;Table;1;pef_content_type;0;pub/runtime/crud/Tablexx1xxtmplFormNg;pub/runtime/cache;;*;7089
|tmplFormNgFieldSet;Table;1;pef_content_type;0;pub/runtime/crud/Tablexx1xxtmplFormNgFieldSet;pub/runtime/cache;;*;7174
|tmplGridNg;Table;1;pef_content_type;0;pub/runtime/crud/Tablexx1xxtmplGridNg;pub/runtime/cache;;*;7087
|tmplGridNgSql;Sql;1;dibqsItems;0;pub/runtime/crud/Sqlxx1xxtmplGridNgSql;pub/runtime/cache;;*;7132
|wizBuildApp;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7234
|wizBuildAppAdv;Table;1;pef_database;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxwizBuildAppAdv;dropinbase/dropins/setNgMaterial/dibAdmin/cache;au,bd;*;7235
|wizBuildAppGrid;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxwizBuildAppGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7230
|wizBuildAppWait;None;;;0;;dropinbase/dropins/setNgMaterial/dibAdmin/cache;;*;7307
|wizTableChangesGrid;Table;1;pef_table;0;dropinbase/dropins/setNgMaterial/dibAdmin/crud/Tablexx1xxwizTableChangesGrid;dropinbase/dropins/setNgMaterial/dibAdmin/cache;ac,au,bd;*;7233
|xxxbenCodeForm;Table;8;xxxben_code;0;pub/runtime/crud/Tablexx1xxxxxbenCodeForm;pub/runtime/cache;;*;9169
|xxxbenCodeGrid;Table;8;xxxben_code;0;pub/runtime/crud/Tablexx1xxxxxbenCodeGrid;pub/runtime/cache;;*;9170
|